/**
 * Created by ulyses.parra488 on 10/18/16.
 */

function ad() {
    var someMsg= alert("HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
    "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/" +
        "HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/HACKING IN PROCESS/");

    //This is the code for the New Tabs that open when the user
    //clicks the text box or the body.
    someMsg =window.open("http://www.lingscars.com"); window.open("http://www.theworldsworstwebsiteever.com/")
    window.open("http://www.rudgwicksteamshow.co.uk/"); window.open("http://www.gatesnfences.com/");
    window.open("http://www.jamilin.com/"); window.open("http://www.arngren.net/");

    //This function makes the POP UP repeat and never end.
    for(i=0;i<10;i++){
        alert(someMsg);
    }
}
function convert(degree) {
    var x;
    if (degree == "Celsius") {
        x = document.getElementById("Celsius").value * 9 / 5 + 32;
        document.getElementById("Fahrenheit").value = Math.round(x);
    } else {
        x = (document.getElementById("Fahrenheit").value -32) * 5 / 9;
        document.getElementById("Celsius").value = Math.round(x);
    }
}